[package]
name = "cget"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
indicatif = "0.17"
reqwest = { version = "0.11", features = ["blocking"] }
